databases:
  - name: full-stack-capstone
    databaseName: full_stack_capstone
    user: full_stack_capstone_user

services:
  - type: web
    name: budgetmap-v1
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: full-stack-capstone
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false