databases:
  - name: rails-projects
    databaseName: budget_app_production_ejzz
    user: budget_app_production_ejzz_user

services:
  - type: web
    name: budgetmap-v1
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails-projects
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false